1.1

In [53]:
import pandas as pd

# 1. 用字典创建 DataFrame
data_dict = {
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78],
    'gender': ['男', '女', '男']
}
df1 = pd.DataFrame(data_dict)

1.2

In [56]:
# 2. 查看前1行、形状、列名、数据类型
print("前1行数据：")
print(df1.head(1))
print("\n数据形状：", df1.shape)
print("\n列名：", df1.columns.tolist())
print("\n数据类型：")
print(df1.dtypes)

前1行数据：
  name  score gender
0  Tom     85      男

数据形状： (3, 3)

列名： ['name', 'score', 'gender']

数据类型：
name      object
score      int64
gender    object
dtype: object

1.3

In [29]:
# 3. 用列表创建 DataFrame
data_list = [[1, "A"], [2, "B"], [3, "C"]]
df2 = pd.DataFrame(data_list, columns=['id', 'tag'])
print("\n用列表创建的 DataFrame：")
print(df2)

用列表创建的 DataFrame：
   id tag
0   1   A
1   2   B
2   3   C

2.1

In [30]:
# 直接列名选取
df1[['score', 'gender']]

   score gender
0     85      男
1     92      女
2     78      男

2.2

In [31]:
# 用 loc 按索引标签选取
df1.loc[[0, 2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

2.3

In [58]:
# 布尔索引筛选
df1[df1['score'] > 80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

2.4

In [33]:
import numpy as np
df1['grade'] = np.where(df1['score'] >= 90, '优秀', '良好')
df1[['name','score', 'gender','grade']]

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

2.5

In [62]:
# 删除 gender 列
df_without_gender = df1.drop('gender',axis=1)
df_without_gender

    name  score
0    Tom     85
1  Jerry     92
2   Mike     78

3.1

In [35]:
import pandas as pd
# 创建含缺失值的 DataFrame
data = {"x": [1, None, 3], "y": [None, 5, 6]}
df_missing = pd.DataFrame(data)
# 检测缺失值并统计每列缺失数量
print("缺失值检测结果：")
print(df_missing.isnull())  # 显示每个位置是否为缺失值
print("\n每列缺失值数量：")
print(df_missing.isnull().sum())  # 统计每列缺失值个数

缺失值检测结果：
       x      y
0  False   True
1   True  False
2  False  False

每列缺失值数量：
x    1
y    1
dtype: int64

3.2

In [36]:
# 用 0 填充缺失值
df_fill = df_missing.fillna(0)
print("用 0 填充后的 DataFrame：")
print(df_fill)

# 删除含缺失值的行
df_drop = df_missing.dropna()
print("\n删除含缺失值行后的 DataFrame：")
print(df_drop)

用 0 填充后的 DataFrame：
     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

删除含缺失值行后的 DataFrame：
     x    y
2  3.0  6.0

4.1

In [64]:
# 按 gender 分组，同时计算均值和最大值
group_result = df1.groupby("gender")["score"].agg(["mean", "max"])
print("按 gender 分组的 score 均值和最大值：")
print(group_result)

按 gender 分组的 score 均值和最大值：
        mean  max
gender
女       92.0   92
男       81.5   85

4.2

In [38]:
# 方法1：value_counts() 直接统计
count_result = df1["gender"].value_counts()
print("按 gender 分组的人数统计：")
print(count_result)

# 方法2：groupby + count()
count_result2 = df1.groupby("gender").size()
print("\n按 gender 分组的人数统计：")
print(count_result2)

按 gender 分组的人数统计：
gender
男    2
女    1
Name: count, dtype: int64

按 gender 分组的人数统计：
gender
女    1
男    2
dtype: int64

5.1

In [66]:
df_sorted = df1.sort_values(by='score', ascending=True)
print("按 score 升序排序后的 DataFrame：")
print(df_sorted)

按 score 升序排序后的 DataFrame：
    name  score gender
2   Mike     78      男
0    Tom     85      男
1  Jerry     92      女

5.2

In [40]:
# 添加一行重复数据（Tom,85,男）
new_row = pd.DataFrame([{"name":"Tom", "score":85, "gender":"男","grade":"良好"}])
df_duplicate = pd.concat([df1, new_row], ignore_index=True)
print("添加重复数据后的 DataFrame：")
print(df_duplicate)

# 去重（默认保留第一次出现的行）
df_deduped = df_duplicate.drop_duplicates()
print("\n去重后的 DataFrame：")
print(df_deduped)

添加重复数据后的 DataFrame：
    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好
3    Tom     85      男    良好

去重后的 DataFrame：
    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

6.1

In [41]:
df1 = pd.DataFrame({"id":[1,2], "name":["X","Y"]})
df2 = pd.DataFrame({"id":[1,2], "age":[20,30]})

# 按 id 内连接合并（保留两边共有的 id）
df_merged = pd.merge(df1, df2, on='id', how='inner')
print("横向合并后的 DataFrame：")
print(df_merged)

横向合并后的 DataFrame：
   id name  age
0   1    X   20
1   2    Y   30

6.2

In [42]:
df_a = pd.DataFrame({"val":[1,2]})
df_b = pd.DataFrame({"val":[3,4]})

# 纵向拼接
df_concat = pd.concat([df_a, df_b], ignore_index=True)
print("纵向拼接并重置索引后的 DataFrame：")
print(df_concat)

纵向拼接并重置索引后的 DataFrame：
   val
0    1
1    2
2    3
3    4

7.1

In [43]:
import pandas as pd

# 创建时间列表
dates = ["2025-01-01", "2025-01-02", "2025-01-03"]
df_time = pd.DataFrame({"date": dates})

# 转为 datetime 格式
df_time['date'] = pd.to_datetime(df_time['date'])
print("转换后的时间列：")
print(df_time.dtypes)
print(df_time)

转换后的时间列：
date    datetime64[ns]
dtype: object
        date
0 2025-01-01
1 2025-01-02
2 2025-01-03

7.2

In [44]:
# 提取月份
df_time['month'] = df_time['date'].dt.month
# 提取星期（0=周一，6=周日；也可用dt.day_name()获取星期名称）
df_time['weekday_num'] = df_time['date'].dt.weekday
df_time['weekday_name'] = df_time['date'].dt.day_name()

print("\n提取月份和星期后的 DataFrame：")
print(df_time)

提取月份和星期后的 DataFrame：
        date  month  weekday_num weekday_name
0 2025-01-01      1            2    Wednesday
1 2025-01-02      1            3     Thursday
2 2025-01-03      1            4       Friday

8.1

In [47]:
score_mean = df_sorted['score'].mean()
score_std = df_sorted['score'].std()

# 标准化
df_sorted['score_standardized'] = (df_sorted['score'] - score_mean) / score_std

print("标准化后的 score 列：")
print(df_sorted[['score', 'score_standardized']])

标准化后的 score 列：
   score  score_standardized
2     78                -1.0
0     85                 0.0
1     92                 1.0

8.2

In [49]:
# 使用 pivot_table
pivot_result = df_sorted.pivot_table(
    index='gender', 
    values='score', 
    aggfunc='median'
)

print("\n按 gender 分组的 score 中位数透视表：")
print(pivot_result)

按 gender 分组的 score 中位数透视表：
        score
gender
女        92.0
男        81.5